[package]
name = "hyperzoekt"
version = "0.1.0"
edition = "2021"
authors = ["dcieslak19973 <dcieslak@hotmail.com>"]
description = "A Rust partial port of Sourcegraph's zoekt (search engine)."
license = "Apache-2.0"
repository = "https://github.com/dcieslak19973/hyperzoekt"

[dependencies]

[dev-dependencies]
tempfile = "3"

[workspace]
members = [
	"crates/repo-index",
]
