[package]
name = "zoekt-distributed"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.12"
chrono = { version = "0.4", features = ["serde"] }
# depend on the local workspace crate
zoekt-rs = { path = "../zoekt-rs" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
deadpool-redis = "0.10"
base64 = "0.22"
tracing-subscriber = "0.3"
clap = { version = "4", features = ["derive"] }
toml = "0.7"

[[bin]]
name = "dzr-http-search"
path = "src/bin/dzr-http-search.rs"

[[bin]]
name = "dzr-mcp-search"
path = "src/bin/dzr-mcp-search.rs"

[[bin]]
name = "dzr-indexer"
path = "src/bin/dzr-indexer.rs"

[[bin]]
name = "dzr-admin"
path = "src/bin/dzr-admin.rs"

[dev-dependencies]
# use the zoekt-rs test helpers to make small repo indexes
proptest = "1"
tempfile = "3"
serial_test = "2"

