services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8001:8001"
    command: start --bind 0.0.0.0:8001 --user root --pass root memory
    restart: unless-stopped
    environment:
      SURREAL_CAPS_ALLOW_EXPERIMENTAL: graphql
  # Note: no in-container healthcheck because the surrealdb image may not include curl/wget.
  # An external prober service below performs the HTTP health check instead.

  zoekt-indexer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "7676:7676"
    environment:
      - DISTRIBUTED_ZOEKT_REPO_EVENTS=1
      - REDIS_URL=redis://redis:6379
      # - RUST_LOG=debug      
      - SURREALDB_URL=surrealdb:8001
      - SURREALDB_USERNAME=root
      - SURREALDB_PASSWORD=root
      - SURREAL_DB=repos
      - SURREAL_DB_VERBOSE_PAYLOADS=1
      - SURREAL_NS=zoekt
      - ZOEKTD_BIND_ADDR=0.0.0.0:7676
      - ZOEKT_ENDPOINT=http://zoekt-indexer:7676
    command: ["/app/dzr-indexer", "--host", "0.0.0.0", "--port", "7676"]
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      surrealdb-prober:
        condition: service_healthy

  zoekt-admin:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "7878:7878"
    environment:
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=debug
      - SURREALDB_URL=surrealdb:8001
      - SURREALDB_USERNAME=root
      - SURREALDB_PASSWORD=root
      - SURREAL_DB=repos
      - SURREAL_NS=zoekt
      - ZOEKT_ADMIN_USERNAME=admin
      - ZOEKT_ADMIN_PASSWORD=password
    command: ["/app/dzr-admin", "--host", "0.0.0.0", "--port", "7878"]
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      surrealdb-prober:
        condition: service_healthy

  zoekt-admin-poller:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=debug
      # Poll interval in seconds; override if you want a different cadence
      - SURREALDB_URL=surrealdb:8001
      - SURREALDB_USERNAME=root
      - SURREALDB_PASSWORD=root
      - SURREAL_DB=repos
      - SURREAL_NS=zoekt
      - ZOEKTD_POLL_INTERVAL_SECONDS=30
    command: ["/app/dzr-admin-poller"]
    ports:
      - "9900:9900"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy

  poller-prober:
    image: curlimages/curl:8.3.0
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      zoekt-admin-poller:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://zoekt-admin-poller:9900/health -o /dev/null -w '%{http_code}' | grep -q '^200$'"]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 2s

  zoekt-search:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=debug
      - SURREALDB_URL=surrealdb:8001
      - SURREALDB_USERNAME=root
      - SURREALDB_PASSWORD=root
      - SURREAL_DB=repos
      - SURREAL_NS=zoekt
      - ZOEKTD_BIND_ADDR=0.0.0.0:8080
    command: ["/app/dzr-http-search", "--host", "0.0.0.0", "--port", "8080"]
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      surrealdb-prober:
        condition: service_healthy

  zoekt-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "7979:7979"
    environment:
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=debug
      - SURREALDB_URL=surrealdb:8001
      - SURREALDB_USERNAME=root
      - SURREALDB_PASSWORD=root
      - SURREAL_DB=repos
      - SURREAL_NS=zoekt
      - ZOEKTD_BIND_ADDR=0.0.0.0:7979
    command: ["/app/dzr-mcp-search", "--host", "0.0.0.0", "--port", "7979"]
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      surrealdb-prober:
        condition: service_healthy

  hyperzoekt-indexer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "7677:7677"
    environment:
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=debug
      - SURREALDB_URL=http://surrealdb:8001
      - SURREALDB_USERNAME=root
      - SURREALDB_PASSWORD=root
      - SURREAL_DB=repos
      - SURREAL_NS=zoekt
      # - SURREAL_DB_VERBOSE_PAYLOADS=1
    command: ["/app/hyperzoekt-indexer", "--host", "0.0.0.0", "--port", "7677"]
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      surrealdb-prober:
        condition: service_healthy

  hyperzoekt-webui:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=debug
      - SURREALDB_URL=http://surrealdb:8001
      - SURREALDB_USERNAME=root
      - SURREALDB_PASSWORD=root
      - SURREAL_DB=repos
      - SURREAL_NS=zoekt
    command: ["/app/hyperzoekt-webui", "--host", "0.0.0.0", "--port", "8081"]
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      surrealdb-prober:
        condition: service_healthy

  surrealdb-prober:
    image: curlimages/curl:8.3.0
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      surrealdb:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://surrealdb:8001/health -o /dev/null -w '%{http_code}' | grep -q '^200$'"]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 5s
