name: workspace CI


on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Run rustfmt (workspace)
        run: |
          cargo fmt --all -- --check

      - name: Run clippy (workspace, deny warnings)
        run: |
          cargo clippy --workspace --all-targets -- -D warnings

      - name: Run tests (workspace)
        run: |
          cargo test --workspace --all

