name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v4

      - name: Fail on deprecated GitHub Actions commands
        run: |
          # search repository for deprecated commands that should be replaced with environment files
          set -euo pipefail
          # search, but filter out this workflow file so the check doesn't report its own text
          grep -R --line-number --binary-files=without-match --exclude-dir=.git --exclude-dir=target -e 'set-output' -e 'set-env' . \
            | grep -v '\.github/workflows/ci.yml' | tee /tmp/deprecated_matches || true

          if [ -s /tmp/deprecated_matches ]; then
            echo "::error::Deprecated GitHub Actions command found (set-output or set-env). Replace with environment files: GITHUB_OUTPUT / GITHUB_ENV"
            echo "Matches:" 
            cat /tmp/deprecated_matches
            exit 1
          fi

      - name: Cache cargo registry and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Check formatting
        if: matrix.toolchain == 'stable'
        run: cargo fmt -- --check

      - name: Run clippy
        if: matrix.toolchain == 'stable'
        run: cargo clippy -- -D warnings

  report-ci:
    name: CI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Create CI check-run
        uses: actions/github-script@v6
        with:
          script: |
            const { context, github } = require('@actions/github');
            const sha = context.payload.pull_request ? context.payload.pull_request.head.sha : context.sha;
            // Create a check run named 'CI' and mark it successful if we reached this step
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'CI',
              head_sha: sha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'CI aggregated',
                summary: 'Aggregated CI status from workflow matrix jobs.'
              }
            });
